# Generated by Django 5.2.7 on 2025-10-04 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True, null=True)),
                ('pmc_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('content', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-publication_date', '-created_at'],
                'indexes': [models.Index(fields=['pmc_id'], name='core_articl_pmc_id_5843a8_idx'), models.Index(fields=['publication_date'], name='core_articl_publica_8d6605_idx'), models.Index(fields=['created_at'], name='core_articl_created_cf20cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('messages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['session_id'], name='core_chatse_session_af58aa_idx'), models.Index(fields=['user_identifier'], name='core_chatse_user_id_f610fb_idx'), models.Index(fields=['is_active'], name='core_chatse_is_acti_cd9211_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('topic', models.CharField(max_length=500)),
                ('article_type', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation_time_seconds', models.FloatField(blank=True, null=True)),
                ('source_articles', models.ManyToManyField(blank=True, related_name='generated_from', to='core.article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='core.article')),
            ],
            options={
                'indexes': [models.Index(fields=['article'], name='core_articl_article_69b2f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('results_count', models.IntegerField(default=0)),
                ('user_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to='core.article')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query_text'], name='core_search_query_t_101d13_idx'), models.Index(fields=['created_at'], name='core_search_created_6a437a_idx')],
            },
        ),
    ]
