# Generated by Django 5.2.7 on 2025-10-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('introduction', models.TextField(blank=True)),
                ('current_findings', models.TextField(blank=True)),
                ('controversies', models.TextField(blank=True)),
                ('future_directions', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('full_review', models.TextField()),
                ('articles_count', models.IntegerField(default=0)),
                ('citations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation_time_seconds', models.FloatField(blank=True, null=True)),
                ('source_articles', models.ManyToManyField(related_name='literature_reviews', to='core.article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
